# Gaussion Elimination

First, we need the relevant imports

In [1]:
import numpy as np

Now, we must define our equation using matricies and vectors

In [2]:
A = np.array([[0, 1, 1],
              [1, 0, 1],
              [1, 1, 0]], float)

v = np.array([3, 5, 4], float)

N = len(v)

x = np.empty(N, float)

Now, we will perform guassian elimination using 
$$\vec{a_j} = \vec{a_j} - a_{ji}\vec{a_i}$$
for all $i > j$, where $\vec{a_j}$ is the row vector of the $j$th row. 

And we implement partial pivoting to ensure that the diagonal rows are non-zero. 

In [3]:
for m in range(N):
    
    for i in range(m+1,N):
        if np.abs(A[m,m]) < np.abs(A[i,m]):
            A[[m,i],:] = A[[i,m],:]	
            v[[m,i]] = v[[i,m]]
    
    div = A[m, m]
    A[m, :] /= div
    v[m] /= div
    
    
    for i in range(m+1, N):
        
        mult = A[i, m]
        A[i, :] -= mult * A[m, :]
        v[i] -= mult * v[m]
        
print("A:", A, "\nv:", v)

A: [[ 1.  0.  1.]
 [ 0.  1.  1.]
 [-0. -0.  1.]] 
v: [5. 3. 2.]


Now let's use upper triangle matrix to find the vector $\vec{x}$ using backsubstitution.
$$x_k = v_k - \sum_{i=k+1}^n a_{ki}x_i$$
Make sure to loop from the last $x_k$ since each $x_k$ depends on all those after it.

In [4]:
for m in range(N-1, -1, -1):
    x[m] = v[m] - sum([A[m, i] * x[i] for i in range(m + 1, N)])
    
print(x)

[3. 1. 2.]


Now, combine it all into one method

In [5]:
def solve(A, v):
    N = len(v)
    x = np.empty(N, float)
    
    for m in range(N):
    
        for i in range(m+1,N):
            if np.abs(A[m,m]) < np.abs(A[i,m]):
                A[[m,i],:] = A[[i,m],:]	
                v[[m,i]] = v[[i,m]]

        div = A[m, m]
        A[m, :] /= div
        v[m] /= div

        for i in range(m+1, N):

            mult = A[i, m]
            A[i, :] -= mult * A[m, :]
            v[i] -= mult * v[m]
            
    for m in range(N-1, -1, -1):
        x[m] = v[m] - sum([A[m, i] * x[i] for i in range(m + 1, N)])
    return x

In [9]:
print(solve(A, v))

print(np.linalg.solve(A, v))

[3. 1. 2.]
[3. 1. 2.]
